# Generated by Django 5.2.12 on 2026-03-17 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("household_name", models.CharField(blank=True, max_length=150)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("snowball", "Snowball"),
                            ("avalanche", "Avalanche"),
                            ("custom", "Custom"),
                        ],
                        default="snowball",
                        max_length=20,
                    ),
                ),
                (
                    "extra_monthly_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_balance_snapshot",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("projected_payoff_date", models.DateField(blank=True, null=True)),
                ("projected_months_to_payoff", models.PositiveIntegerField(default=0)),
                (
                    "projected_total_interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "projected_total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DebtItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("lender_name", models.CharField(blank=True, max_length=150)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("apr", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "minimum_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("due_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("custom_order", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debt_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_items",
                        to="plans.debtplan",
                    ),
                ),
            ],
            options={
                "ordering": ["custom_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario_name", models.CharField(max_length=120)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("snowball", "Snowball"),
                            ("avalanche", "Avalanche"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "extra_monthly_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payoff_date", models.DateField(blank=True, null=True)),
                ("months_to_payoff", models.PositiveIntegerField(default=0)),
                (
                    "total_interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debt_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_comparisons",
                        to="plans.debtplan",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
