# Generated by Django 5.2.12 on 2026-03-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariocomparison",
            name="is_system_generated",
            field=models.BooleanField(default=False),
        ),
    ]
