# Generated by Django 5.2.12 on 2026-03-19 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0003_mark_existing_scenarios_as_system_generated"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="debtitem",
            name="debt_type",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("vehicle", "Vehicle"),
                    ("mortgage", "Mortgage"),
                    ("bank_loan", "Bank Loan"),
                    ("payday_loan", "Payday Loan"),
                    ("personal_loan", "Personal Loan"),
                    ("student_loan", "Student Loan"),
                    ("other_debt", "Other Debt"),
                ],
                default="other_debt",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="debtplan",
            name="checkin_anchor_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="debtplan",
            name="checkins_active",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BadgeAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge_key", models.CharField(max_length=64)),
                ("badge_name", models.CharField(max_length=120)),
                ("badge_image", models.CharField(max_length=255)),
                ("debt_type", models.CharField(max_length=32)),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debt_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_awards",
                        to="plans.debtitem",
                    ),
                ),
                (
                    "debt_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_awards",
                        to="plans.debtplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("debt_item", "badge_key"),
                        name="unique_badge_award_per_debt",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_index", models.PositiveIntegerField()),
                ("month_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "Made payments as planned"),
                            ("skipped_extra", "Skipped extra payment"),
                            ("custom", "Adjusted extra payment"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "extra_payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debt_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_checkins",
                        to="plans.debtplan",
                    ),
                ),
            ],
            options={
                "ordering": ["month_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("debt_plan", "month_index"),
                        name="unique_monthly_checkin_per_plan_month",
                    )
                ],
            },
        ),
    ]
