# Generated by Django 5.2.12 on 2026-03-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionaccess",
            name="stripe_cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionaccess",
            name="stripe_current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionaccess",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="subscriptionaccess",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="subscriptionaccess",
            name="stripe_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="subscriptionaccess",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
