# Generated by Django 5.2.12 on 2026-03-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_subscriptionaccess_stripe_cancel_at_period_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="google_avatar_url",
            field=models.URLField(blank=True),
        ),
    ]
